# Copyright (C) 2010 nineties
#
# $Id: Syntax.ab 2014-01-23 03:10:16 nineties $

# Extensions of syntax for shell mode.

primary_expr ::= "%" decimal
                 {
                    if ($1 == 0 or $1 > size(shell_outputs)) {
                        throw `Error{!LOCATION, "The argument of % must be a line number"}
                    }
                    `shell_outputs[!$1]
                 }
                     | "%"         { `shell_outputs[0] }

Syntax.primary_expr |= primary_expr
