# $Id: string.ab 2012-07-25 13:02:11 nineties $

include "unittest.ab"
import unittest

test "string module" {
    # XXX: should use randomlly generated strings.
    "equality"   { "" == "" &&  "Hello World" == "Hello World" }
    "inequality" { "abcdefg" != "gfedcba" }
    "to_s"       { "Hello World".to_s == "Hello World" }
    "add 1"      { "Hello" + " " + "World" == "Hello World" }
    "unescape"   { "Hello World\\n".unescape == "Hello World\n" }
}
