# $Id: string.ab 2012-11-27 00:17:11 nineties $

import unittest

test "string module" {
    # XXX: should use randomly generated strings.
    "equality":   { "" == "" and  "Hello World" == "Hello World" }
    "inequality": { "abcdefg" != "gfedcba" }
    "to_s":       { "Hello World".to_s == "Hello World" }
    "add":        { "Hello" + " " + "World" == "Hello World" }
    "unescape":   { "Hello World\\n".unescape == "Hello World\n" }
}
