# Copyright (C) 2014 nineties
# $Id: amber/typing.ab 2014-04-30 18:54:59 nineties $

#= Type-analysis of amber programs =

import amber::defuse (defuse_analysis)
import amber::typing::inference (type_inference)

analyze(compiler) := {
    compiler.log("Typing %s...\n", compiler.input_file)
    compiler.log(1, "Use-definition analysis")
    defuse_analysis(compiler)
    compiler.log(1, "Probabilistic type inference\n")
    type_inference(compiler)
}
