# Copyright (C) 2014 nineties
# $Id: IO/InputStringStream.ab 2014-02-11 20:12:21 nineties $

InputStringStreamTrait: Prim.InputStringStreamTrait with {
    parent        = InputStreamTrait
    lookahead()   = Prim.iss_lookahead(self)
    read_char()   = Prim.iss_read_char(self)
    read_string() = Prim.iss_read_string(self)
    read_line()   = Prim.iss_read_line(self)
}

new: Prim.iss_new

export InputStringStreamTrait
