# Copyright (C) 2012 nineties
#
# $Id: array.ab 2012-12-07 00:31:14 nineties $

module std {
    Array{elems...} => `(Array::from_list !elems)

    each ary@Array: {
        i: 0
        n: ary.size
        () -> {
            if (i >= n) return undefined
            v: ary[i]
            i += 1
            v
        }
    }

    reverse_each ary@Array: {
        i: ary.size
        () -> {
            if (i == 0) return undefined
            i -= 1
            ary[i]
        }
    }
}
