# Copyright (C) 2012 nineties
#
# $Id: string.ab 2012-12-08 13:04:16 nineties $

module std {
    each(str@String): {
        i: 0
        n: str.size
        () -> {
            if (i >= n) return undefined
            v: str[i]
            i += 1
            v
        }
    }

    reverse_each(str@String): {
        i: str.size
        () -> {
            if (i == 0) return undefined
            i -= 1
            str[i]
        }
    }
}
