# Copyright (C) 2012 nineties
#
# $Id: table.ab 2013-03-05 04:44:39 nineties $

module Std {
    module Parser {
        table_entry ::= expr "=>" expr { ($0, $2) }
        postfix_expr
            ::= <<multiline>> "Table" "{" delimited(table_entry, ",") "}"
                { `Table::from_list(!$2) }
    }

    each(tbl@Table): tbl.entries.each
    reverse_each(tbl@Table): tbl.entries.reverse_each
}
