# Copyright (C) 2014 nineties
# $Id: CAST/compile.ab 2014-04-23 17:30:04 nineties $

import amber
import CAST::template as T
import CAST::Cgen as GEN

# Change working directory to the original path.
sys::chdir(INVOKE_PATH)

if Compiler.input_language != amber
    throw `Error{
        "Sorry, CAST-compiler doesn't support this language",
        !Compiler.input_language
    }

amber::typing::analyze(Compiler)

GEN::generate(Compiler, T::main)

throw "Not implemented"
