# Copyright (C) 2014 nineties
# $Id: CAST/compile.ab 2014-04-22 17:56:30 nineties $

# Change working directory to the original path.
sys::chdir(INVOKE_PATH)

if CompileState.input_language != amber
    throw `Error{
        "Sorry CAST-compiler doesn't support this input_language",
        !CompileState.input_language
    }

import CAST::template as T
import CAST::Cgen as GEN

puts sys::getcwd()
GEN::generate(CompileState, T::main)

throw "Not implemented"
