# Copyright (C) 2014 nineties
# $Id: algebra/data.ab 2014-04-13 08:10:35 nineties $

#= Basic data constructors =

UNARY_OPERATORS := '[UPlus, UMinus, Not]

for f in UNARY_OPERATORS {
    Algebra.set_slot(f.downcase(),
        eval(`(a -> self.simplify(node('!f, a)))))
}

BINARY_OPERATORS :=
    '[Add, Sub, Mul, Quo, NcMul, Mod, Pow, And, Or, Lt, Gt, Le, Ge, Eq, Ne]

for f in BINARY_OPERATORS {
    Algebra.set_slot(f.downcase(),
        eval(`((a,b) -> self.simplify(node('!f, a, b)))))
}
