# Copyright (C) 2014 nineties
# $Id: CAST.ab 2014-03-15 17:09:33 nineties $

#= CAST: The C-based Abstract Syntax Tree =
# CAST is a C-based intermediate language. It was introduced in "Flick"
# project. The language defined in this library is not exactly C, but
# its implementaion is done by reference to the project.
# * Flick project: http://www.cs.utah.edu/flux/flick/current/doc/guts/guts.html#gutspa2.html

import AST
