# Copyright (C) 2014 nineties
# $Id: GC.ab 2015-06-07 14:59:32 nineties $

start() := prim.GC_start()

# return (used memsize, allocated memsize) in bytes
stats(format=false) := {
    unless format
        return prim.GC_stats()
    used, alloc := prim.GC_stats()
    io::format("used: %.2fM bytes, alloc: %.2fM bytes, usage: %.2f%%",
        used/(1024^2), alloc/(1024^2), used/alloc*100)
}

addressof(obj) := prim.GC_addressof(obj)
