# Copyright (C) 2013 nineties
#
# $Id: oop.ab 2013-02-05 14:55:11 nineties $

# Prototype-based Object-Oriented Programming

module std {
    object_slot  ::= symbol ":" expr { ($0, $2) }
    object_slots
        ::= [multiline] "{" delimited(object_slot, ",") "}" { $1 }
          | [multiline] "{" aligned(object_slot) "}"        { $1 }

    object_creation
        ::= [multiline] symbol object_slots { `make_object(\!$0, \!$1) }

    postfix_expr ::= object_creation
}
