# Copyright (C) 2014 nineties
# $Id: Parser.ab 2014-02-10 15:07:53 nineties $

new(ichan): Prim.parser_new(ichan)

ParserTrait: Prim.ParserTrait with {
    parse_shell()    = Prim.parse_shell(self)
    parse_toplevel() = Prim.parse_toplevel(self)
    node             = alias(() -> Prim.parser_node(self))
    error_string     = alias(() -> Prim.parser_error(self))
    loc              = alias(() -> Prim.parser_loc(self))
    flush()          = Prim.parser_flush(self)
}
