# Copyright (C) 2014 nineties
# $Id: Symbol.ab 2014-02-12 14:55:25 nineties $

import String

SymbolTrait: Prim.SymbolTrait

StringTrait.to_sym(): Prim.string_to_symbol(self)
StringTrait.intern: StringTrait.to_sym

SymbolTrait.to_s(): Prim.symbol_to_string(self)
SymbolTrait.hash(): Prim.symbol_hash(self)

unique_sym: Prim.unique_symbol
hash = Prim.symbol_hash | hash

export SymbolTrait unique_sym
