# Copyright (C) 2014 nineties
# $Id: sys.ab 2014-04-23 23:47:49 nineties $

#= Operation System interface =

# Change directory to `path`.
# Exception: OSError
chdir := prim.chdir

# Get path of current working directory.
# Exception: OSError
getcwd := prim.getcwd

# Return true when the file exists.
exist? := prim.file_exist?

# Return `mtime` of the file.
# Exception: OSError
mtime := prim.mtime
