try {
    throw "You can throw any value"
} catch e -> {
    puts(e)
}

try {
    throw `Exception{"You can use pattern matching"}
} catch Exception{msg} -> {
    puts(msg)
}

try {
    throw `ExceptionBar{"You can use multiple patterns"}
} catch
      ExceptionFoo{msg} -> { puts("Exception Foo") } 
    | ExceptionBar{msg} -> { puts("Exception Bar") } 
    | ExceptionBaz{msg} -> { puts("Exception Baz") }
