# Copyright (C) 2014 nineties
# $Id: symbolic/basic.ab 2014-04-21 18:41:48 nineties $

#= Basic functions for symbolic computation =

# `depend?(e, x)` returns `true` when the expression `e` depends on the
# variable `x`.
depend? := (x, x)            -> true
         | (_ @ Symbol, _)   -> false
         | (_ @ Int, _)      -> false
         | (_ @ Float, _)    -> false
         | (o, x)            -> o.arguments.any?(a -> depend?(a, x))
