# Copyright (C) 2014 nineties
# $Id: Numeric/Random.ab 2014-03-04 23:11:25 nineties $

# Initialize random seed.
srand(): Prim.srand()

# Initialize random seed by `seed`.
srand(seed): Prim.srand_with_value(seed)

# Return random floating number in range [0,1).
rand(): Prim.rand_uniform()

# Return random floating number in range [0,v).
rand(v @ Float): Prim.rand_float(v)

# Return random integer in range [0,n).
rand(n @ Int):     Prim.rand_int(n)
rand(n @ BigIntE): Prim.rand_bint(n)
