# Copyright (C) 2012 nineties
#
# $Id: array.ab 2012-12-16 01:53:20 nineties $

module Std {
    each(ary@Array): {
        i: 0
        n: ary.size
        () -> {
            if (i >= n) return undef
            v: ary[i]
            i += 1
            v
        }
    }

    reverse_each(ary@Array): {
        i: ary.size
        () -> {
            if (i == 0) return undef
            i -= 1
            ary[i]
        }
    }
}
