#!/usr/bin/amber

# amber - 2nd generation
# Copyright (C) 2010 nineties
#
# $Id: main.ab 2012-01-26 02:07:49 nineties $

# recursive function
fib(n): fib(n-1) + fib(n-2)
fib(1): 1
fib(2): 1

puts(fib(20))

# mutual recursive function
even(n): odd(n-1)
even(0): true
odd(n): even(n-1)
odd(0): false

puts(even(0))
puts(odd(0))
puts(even(9))
puts(odd(1))

## test of updating variable-display
module M {
    x: 1
    module N { }
}
puts(M::N::x) # => 1
module M::N {
    x: 2
}
puts(M::N::x) # => 2
